version: '3.1'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
    ports:
      - 1521:1521

    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  spring-boot-app:
    build:
      context: ./UsersApp
      dockerfile: Dockerfile
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8081:8081"

  react-front-app:
    build:
      context: ./users-app-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot-app

volumes:
  oracle-data:
  oracle-backup:

  
